# Generated by Django 5.1.6 on 2025-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_robot_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='map',
            field=models.BooleanField(default=False),
        ),
    ]
