# Generated by Django 5.1.6 on 2025-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_robot_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='Break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robot',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
