# Generated by Django 5.1.6 on 2025-03-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_robot_break_robot_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='Break',
            new_name='emergency_stop',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='emergency',
            new_name='motor_brake_released',
        ),
        migrations.AddField(
            model_name='robot',
            name='ready_to_navigate',
            field=models.BooleanField(default=False),
        ),
    ]
