# Generated by Django 5.1.6 on 2025-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_rename_break_robot_emergency_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='volume',
            field=models.IntegerField(default=50),
        ),
    ]
