# Generated by Django 5.1.6 on 2025-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_robot_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.BooleanField(default=False)),
                ('waiting', models.BooleanField(default=False)),
                ('speaking', models.BooleanField(default=False)),
            ],
        ),
    ]
