# Generated by Django 5.1.6 on 2025-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_lastclickednavigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robo_id', models.CharField(max_length=255, unique=True)),
                ('volume', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
